### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by davy932** [lopelex/harmony-websocket#11]
Hi:
Setup:

Home Assistant on Pi4
Supervisor Version: 2020.12.7
Home Assistant OS 5.8

Trying to install the Nodes and get the following in the log:

-----------------------------------------------------------
2020-12-16T22:51:28.299Z Install : node-red-contrib-harmony-websocket 2.2.4

2020-12-16T22:51:30.901Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-harmony-websocket@2.2.4
2020-12-16T22:51:43.862Z [out] 
2020-12-16T22:51:43.862Z [out] > bufferutil@4.0.2 install /config/node-red/node_modules/bufferutil
2020-12-16T22:51:43.862Z [out] > node-gyp-build
2020-12-16T22:51:43.862Z [out] 
2020-12-16T22:51:46.177Z [err] gyp
2020-12-16T22:51:46.178Z [err]  
2020-12-16T22:51:46.178Z [err] ERR! build error 
2020-12-16T22:51:46.179Z [err] gyp
2020-12-16T22:51:46.180Z [err]  ERR! stack
2020-12-16T22:51:46.180Z [err]  Error: not found: make
2020-12-16T22:51:46.180Z [err] gyp ERR! 
2020-12-16T22:51:46.180Z [err] stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-12-16T22:51:46.180Z [err] gyp ERR! 
2020-12-16T22:51:46.180Z [err] stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-12-16T22:51:46.180Z [err] gyp ERR! 
2020-12-16T22:51:46.181Z [err] stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-12-16T22:51:46.181Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-12-16T22:51:46.181Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-12-16T22:51:46.181Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-12-16T22:51:46.181Z [err] gyp 
2020-12-16T22:51:46.182Z [err] ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
2020-12-16T22:51:46.183Z [err] gyp ERR! System Linux 5.4.79-v8
2020-12-16T22:51:46.183Z [err] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-12-16T22:51:46.183Z [err] gyp ERR! cwd /config/node-red/node_modules/bufferutil
2020-12-16T22:51:46.183Z [err] gyp ERR! node -v v12.18.4
2020-12-16T22:51:46.184Z [err] gyp ERR! node-gyp -v v5.1.0
2020-12-16T22:51:46.184Z [err] gyp ERR! not ok
2020-12-16T22:51:46.184Z [err]  
2020-12-16T22:51:46.868Z [err] npm
2020-12-16T22:51:46.868Z [err]  WARN multiple-select@1.5.2 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
2020-12-16T22:51:46.869Z [err] 
2020-12-16T22:51:46.892Z [err] npm ERR!
2020-12-16T22:51:46.892Z [err]  code ELIFECYCLE
2020-12-16T22:51:46.892Z [err] npm ERR! 
2020-12-16T22:51:46.892Z [err] errno 1
2020-12-16T22:51:46.900Z [err] npm 
2020-12-16T22:51:46.900Z [err] ERR! bufferutil@4.0.2 install: `node-gyp-build`
2020-12-16T22:51:46.900Z [err] npm ERR! Exit status 1
2020-12-16T22:51:46.901Z [err] npm ERR! 
2020-12-16T22:51:46.901Z [err] npm ERR! Failed at the bufferutil@4.0.2 install script.
2020-12-16T22:51:46.901Z [err] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-12-16T22:51:46.923Z [err] 
2020-12-16T22:51:46.923Z [err] npm ERR! A complete log of this run can be found in:
2020-12-16T22:51:46.923Z [err] npm ERR!     /root/.npm/_logs/2020-12-16T22_51_46_911Z-debug.log
2020-12-16T22:51:46.954Z rc=1

Any help would be much appreciated

**Comment by lopelex** [comment]
https://github.com/lopelex/node-red-contrib-harmony/issues/17

**Comment by lopelex** [comment]
https://github.com/lopelex/node-red-contrib-harmony/issues/17#issuecomment-770268032
