### ISSUE TITLE
WebSocket exception crashes a node-red server

### ISSUE THREAD

**Issue by benkap** [lopelex/harmony-websocket#8]
First thank you for this great work! 90% of my home automation relay on this npm (using node-red-contrib-harmony in node-red) and it's a life saver.

From time to time (I couldn't find any specific trigger) an exception is thrown and kills node-red completely:

`
Error: Can't send data because WebSocket is not opened.
    at exports.throwIf (/share/CACHEDEV1_DATA/homes/admin/.node-red/node_modules/harmony-websocket/node_modules/websocket-as-promised/dist/index.js:3470:11)
    at WebSocketAsPromised.send (/share/CACHEDEV1_DATA/homes/admin/.node-red/node_modules/harmony-websocket/node_modules/websocket-as-promised/dist/index.js:554:7)
    at Timeout._interval.setInterval [as _onTimeout] (/share/CACHEDEV1_DATA/homes/admin/.node-red/node_modules/harmony-websocket/lib/harmony-websocket.js:136:59)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
`

At first I thought that i used too many "Harmony-Observe" nodes since the harmony hub is really not that reliable and maybe too many open sockets start some snowball and crashes, but after re-design all my flows to use only one main "Harmony-Observe" node-red still crashes (at least once a day or two).

I am using node 8.9.4 and node-red 0.20.6 but on ARM system (Qnap TS-431p).

I don't care about the exception (and probably the Harmony hub is really not open) but since it kill node-red it's a bugger issue.
I wasn't sure if to open on node-red-contrib-harmony repo since the exception is more related to harmony-websocket but maybe node-red-contrib-harmony should handle the exception better so let me know if to move this to [node-red-contrib-harmony repo](https://github.com/lopelex/node-red-contrib-harmony).

What do you think?

**Comment by lopelex** [comment]
Thanks for the hint. 
It is probably not always an onClose event triggered by websocket-as-promised. 
A simple try catch should be the easiest solution here.
see https://github.com/lopelex/harmony-websocket/commit/3995c3e3d19384b1355bc406fed29eacb388d58b#diff-c8eab4317301da541e2bbd5a305d145fR136
